title: AKnownUser Research

description: Blog that contains my research and learning process in IR and malware analysis
github_username: aknownuser

#Site author
author:
  name: "Oussama El Azizi"
  bio: "Interested in malware and analysing stuff"
  location: "Barcelona, Spain"
  links:
    - label: "LinkedIn"
      incon: "fab fa-fw fa-linkedin" 
      url: "www.linkedin.com/in/oussama-el-azizi-b67815110"
#Builds settings
plugins: [ "jekyll-include-cache" ]
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
